dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - aave/aave-v3-core@1.13.0
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@aave-core=aave/aave-v3-core@1.13.0'
      - '@aave=aave/protocol-v2@1.0.1'
dotenv: .env
networks:
  default: mumbai
  mumbai:
    weth_token: '0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa'
    lending_pool_addresses_provider: '0xd05e3E715d945B59290df0ae8eF85c1BdB684744'
    lending_pool_addresses_provider_v3: '0x5343b5bA672Ae99d627A1C87866b8E53F47Db2E6'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
    verify: False
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    lending_pool_addresses_provider: '0x88757f2f99175387ab4c6a4b3067c77a695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}